config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root to: "forums#index"
  devise_for :users

  resources :forums do
    member do
      put "like",    to: "forums#upvote"
      put "dislike", to: "forums#downvote"
    end
    resources :comments
  end
  resources :news
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/forum.rb
class Forum < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :forums
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable
  #authenticate current_user before performing actions
  before_action :authenticate_user!, except:[:index, :show]
  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(params[:comment].permit(:content))
    if @comment.save
      redirect_to @commentable, notice: "Comment created."
    else
      render :new
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    if @comment.destroy
      redirect_to @commentable, notice: "Deleted comment"
    else
      redirect_to @commentable, notice: "Unable to delete comment!"
    end
  end

  private

  def load_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy,:upvote,:downvote]
  #authenticate current_user before performing actions
  before_action :authenticate_user!, except:[:index, :show]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @forum = Forum.find(params[:id])
    @commentable = @forum
    @comments = @commentable.comments
    @comment = Comment.new
  end

  # GET /forums/new
  def new
    @forum = current_user.forums.build
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = current_user.forums.build(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #upvote method
  def upvote
    #assign upvote to current user
    @forum.upvote_by current_user
    #back redirects the current user to the page they where currently on
    redirect_back(fallback_location: root_path)
  end

  #downvote method/action
  def downvote
    #assign downvote to current user
    @forum.downvote_by current_user
    #back redirects the current user to the page they where currently on
    redirect_back(fallback_location: root_path)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_forum
    @forum = Forum.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def forum_params
    params.require(:forum).permit(:title, :question, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  #authenticate current_user before performing actions
  before_action :authenticate_user!, except:[:index, :show]

  # GET /reviews
  # GET /reviews.json
  def index
    @igdb_reviews = JSON.parse(GetReviews.gamereviews)
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def review_params
    params.require(:review).permit(:title, :introduction, :content, :platform, :rating_category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/comments/_comments.html.erb
<div id="comments">
  <% @comments.each do |comment| %>
    <div class="comment">
      <%= simple_format comment.content %>
      <%= link_to "Delete Comment",[comment.commentable, comment],method: :delete, data:{confirm:'Are you sure?'} %>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<h1>New Comment</h1>

<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, rows: 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>
<%= render 'comments' %>
<p><%= link_to "New Comment", [:new, @commentable, :comment] %></p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, rows: 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/_form.html.erb
<%= form_with(model: forum, local: true) do |form| %>
  <% if forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :question %>
    <%= form.text_area :question, class: "form-control" %>
  </div>

  <div class="class: "form-control"">
    <%= form.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<div class="forums-wrapper">
	<h1 style="color: #F05F40;text-align: center;"><i>FORUMS</i></h1>
	<hr>
	<% @forums.each do |forum| %>
	<div class="forum clearfix">
		<h2>
		<%= link_to forum.title,forum %><br>
		<small class="author">Created <%= time_ago_in_words(forum.created_at) %> by <%=forum.user.email%></small>
		</h2>
		<!--UPVOTE AND DOWNVOTE-->
		<div class="btn-group">
			<%= link_to "Checkout Forum", forum_path(forum),class:"btn btn-default btn-sn"%>
			<%=link_to like_forum_path(forum), method: :put, class: "btn btn-default btn-sn" do %>
			<span class="glyphicon glyphicon-chevron-up"></span>
			Upvote
			<%=forum.get_upvotes.size%>
			<%end%>
			<%=link_to dislike_forum_path(forum), method: :put, class: "btn btn-default btn-sn" do %>
			<span class="glyphicon glyphicon-chevron-down"></span>
			Downvote
			<%=forum.get_downvotes.size%>
			<%end%>
		</div>
	</div>
	<%end%>
</div>

app/views/forums/new.html.erb
<h1>New Forum</h1>

<%= render 'form', forum: @forum %>
<br>
<%= link_to 'Back', forums_path, class:"btn btn-default" %>

app/views/forums/show.html.erb
<div class="page-header">
	<h1><%=@forum.title%><br>
	<small>Submitted by <%=@forum.user.email%> </small></h1>
	<h3>Question:<%=@forum.question%></h3>
</div>

<div class="btn-group">
	<%= link_to 'Back', forums_path, class: "btn btn-default" %>
	<% if @forum.user == current_user%>
	<%= link_to 'Edit', edit_forum_path(@forum), class:  "btn btn-default" %>
	<%= link_to 'Destroy', @forum, method: :delete, data:{confirm:'Are you sure?'}, class:"btn btn-default" %>
</div>
<%end%>
<!--UPVOTE & DOWNVOTE-->
<div class="btn-group pull-right">
	<%=link_to like_forum_path(@forum), method: :put, class: "btn btn-default btn-sn" do %>
	<span class="glyphicon glyphicon-chevron-up"></span>
	Upvote
	<%=@forum.get_upvotes.size%>
	<%end%>
	<%=link_to dislike_forum_path(@forum), method: :put, class: "btn btn-default btn-sn" do %>
	<span class="glyphicon glyphicon-chevron-down"></span>
	Downvote
	<%=@forum.get_downvotes.size%>
	<%end%>
</div>

<h2><%=@forum.comments.count%> Comments</h2>

<%= render "comments/comments" %>
<%= render "comments/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>GameBuddy</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<script src="https://use.fontawesome.com/16181c0ef9.js"></script>
	</head>
	<body>
		<header class="navbar navbar-default" role="navigation">
			<div class="navbar-inner">
				<div class="container">
					<div id="logo" class="navbar-brand"><%= link_to "GameBuddy", root_path %></div>
					<nav class="collapse navbar-collapse navbar-ex1-collapse">
						<!--Conditional stmt to show if user has signed in or not-->
						<%if user_signed_in?%>
						<ul class="nav navbar-nav navbar-right">
							<li><%= link_to 'Forums', forums_path %></li>
							<li><%= link_to 'Reviews', reviews_path %></li>
							<li><%= link_to 'News', news_index_path %></li>
							<li><%= link_to 'Account', edit_user_registration_path %></li>
							<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
						</ul>
						<%else%>
						<ul class="nav navbar-nav pull-right">
							<li><%= link_to 'Forums', forums_path %></li>
							<li><%= link_to 'Reviews', reviews_path %></li>
							<li><%= link_to 'News', news_index_path %></li>
							<li><%= link_to 'Sign up', new_user_registration_path %></li>
							<li><%= link_to 'Sign in', new_user_session_path %></li>
						</ul>
						<%end%>
					</nav>
				</div>
			</div>
		</header>
		<div class="container">
			<!--Added flash msg-->
			<% flash.each do |name,msg| %>
			<!--Added alert class based on what type of alert it is-->
			<%= content_tag(:div, msg, class:"alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<!--FOOTER-->
			<footer class="footer-distributed">
				<div class="footer-left">
					<h3 style="color: #F05F40">GameBuddy</h3>
					<p class="footer-links">
						<a href="#">Home</a>
						·
						<a href="#">Reviews</a>
						·
						<a href="#">News</a>
						·
						<a href="#">About</a>
						·
						<a href="#">Faq</a>
						·
						<a href="#">Contact</a>
					</p>
					<p class="footer-company-name">GameBuddy &copy; 2017</p>
					<div class="footer-icons">
						<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-instagram"></i></a>
						<a href="#"><i class="fa fa-github"></i></a>
					</div>
				</div>
				<div class="footer-right">
					<p>Contact Us</p>
					<form action="#" method="post">
						<input type="text" name="email" placeholder="Email" />
						<textarea name="message" placeholder="Message"></textarea>
						<button>Send</button>
					</form>
				</div>
			</footer>
		</div>
	</body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :review_title %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_field :introduction, id: :review_introduction %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :review_content %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.text_field :platform, id: :review_platform %>
  </div>

  <div class="field">
    <%= form.label :rating_category %>
    <%= form.number_field :rating_category, id: :review_rating_category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<div style="text-align: center;" class="reviews-wrapper">
	<h1 style="color: white;">Reviews</h1>
	<hr>
	<% @reviews.each do |review| %>
	<div class="my-reviews">
		<h1><%= link_to review.title,review, style:"color:#F05F40" %></h1>
		<hr style="width: 20%">
		<h2><%=review.introduction%></h2>
		<small class="author">Submitted <%=time_ago_in_words(review.created_at) %> ago by <%=review.user.email%></small><br>
		<%= link_to "See More", review_path(review)%>
	</div>
	<%end%>
	<hr>
	<%if user_signed_in?%>
	<%= link_to 'Create New Review', new_review_path, class:"btn btn-primary" %>
	<%end%>
	<div class="other-reviews-wrapper">
		<h1 style="color: white">Other Reviews</h1>
		<% @igdb_reviews.each do |review|%>
		<div class="other-review">
			<h1><%= review["title"] %></h1>
			<hr style="width: 20%;">
			<h2><%= review["introduction"]%></h2>
			<p><%= review["content"] %></p>
			<p>RATING: <%= review["rating_category"]%></p>
		</div>
		<%end%>
	</div>
</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<div class="page-header" style="color: white">
  <h1 style="color: #F05F40"><%=@review.title%></h1>
  <h2><%= @review.introduction%></h2>
  <p><%= @review.content%><p>
  <p>Platform: <%= @review.platform%></p>
  <p>RATING: <%= @review.rating_category%></p>
  <small>Submitted by <%=@review.user.email%></small>
</div>
<div class="btn-group">
  <%= link_to 'Back', reviews_path, class: "btn btn-default" %>
  <% if @review.user == current_user%>
  <%= link_to 'Edit', edit_review_path(@review), class:  "btn btn-default" %>
  <%= link_to 'Destroy', @review, method: :delete, data:{confirm:'Are you sure?'}, class:"btn btn-default" %>
</div>
<%end%>